[package]
name = "PortfolioWebsite"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-files = "0.6"
actix-web = { version = "4", features = ["rustls"] }
rustls = "0.23.13"
tokio = { version = "1.40.0", features = ["full"] }
